// Copyright 2023 Innkeeper lanmengyou(殷家豪)&lt;2058818914@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/lanyoumeng/myblog.git.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: myblog/v1/myblog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyBlogClient is the client API for MyBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyBlogClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type myBlogClient struct {
	cc grpc.ClientConnInterface
}

func NewMyBlogClient(cc grpc.ClientConnInterface) MyBlogClient {
	return &myBlogClient{cc}
}

func (c *myBlogClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/v1.MyBlog/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyBlogServer is the server API for MyBlog service.
// All implementations must embed UnimplementedMyBlogServer
// for forward compatibility
type MyBlogServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedMyBlogServer()
}

// UnimplementedMyBlogServer must be embedded to have forward compatible implementations.
type UnimplementedMyBlogServer struct {
}

func (UnimplementedMyBlogServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedMyBlogServer) mustEmbedUnimplementedMyBlogServer() {}

// UnsafeMyBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyBlogServer will
// result in compilation errors.
type UnsafeMyBlogServer interface {
	mustEmbedUnimplementedMyBlogServer()
}

func RegisterMyBlogServer(s grpc.ServiceRegistrar, srv MyBlogServer) {
	s.RegisterService(&MyBlog_ServiceDesc, srv)
}

func _MyBlog_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyBlogServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MyBlog/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyBlogServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyBlog_ServiceDesc is the grpc.ServiceDesc for MyBlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyBlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MyBlog",
	HandlerType: (*MyBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _MyBlog_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myblog/v1/myblog.proto",
}
